import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import MyPieChart from './MyPiechart';
import jsPDF from 'jspdf';
import aboutLogo from '../images/aditya-logo.webp';

const OthersClass = ({ Id }) => {
  const [classes, setClasses] = useState([]);
  const navigate = useNavigate();

  // Function to generate chart data for each class
  const generateChartData = (classItem) => {
    const data = {
      above95: classItem.above95 || 0,
      between85And95: classItem.between85And95 || 0,
      between75And85: classItem.between75And85 || 0,
      below75: classItem.below75 || 0,
      passPercentage: classItem.passPercentage || 0,
    };
    console.log("Generated chartData:", data); // Check here
    return data;
  };
  

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(`http://localhost:5000/update/otherclass/${Id}`);
        if (response.ok) {
          const data = await response.json();
          setClasses(data);
          console.log("Fetched data:", data);
        } else {
          console.error("Error:", response.statusText);
        }
      } catch (error) {
        console.error("Fetch error:", error);
      }
    };
    fetchData();
  }, [Id]);

  // Function to download PDF (similar to DisplayClasses)
  const downloadPDF = async () => {
    const doc = new jsPDF();
    const viteLogo = new Image();
    viteLogo.src = aboutLogo;

    viteLogo.onload = () => {
      doc.addImage(viteLogo, 'JPEG', 10, 5, 30, 15);
      doc.setFontSize(20);
      doc.text('Aditya College', 50, 15);
      doc.setFontSize(12);
      doc.text('Faculty Evaluation Report', 50, 25);
      doc.setDrawColor(0, 0, 0);
      doc.line(10, 30, 200, 30);

      const tableStartY = 40;
      const headers = [
        { name: 'Course Name', width: 50 },
        { name: 'Attended', width: 30 },
        { name: 'Semester', width: 30 },
        { name: 'Branch', width: 30 },
        { name: 'Section', width: 20 },
        { name: 'Students', width: 30 },
        { name: 'Pass %', width: 30 },
      ];

      let currentX = 10;
      headers.forEach((header) => {
        doc.text(header.name, currentX, tableStartY);
        currentX += header.width;
      });

      let rowY = tableStartY + 10;
      doc.setFontSize(10);

      classes.forEach((classItem) => {
        currentX = 10;
        const rowData = [
          classItem.courseName,
          classItem.appeared.toString(),
          classItem.semester,
          classItem.branch,
          classItem.section,
          classItem.numberOfStudents.toString(),
          `${classItem.passPercentage}%`,
        ];

        rowData.forEach((data, index) => {
          doc.text(data, currentX, rowY);
          currentX += headers[index].width;
        });

        rowY += 8;
        if (rowY > 260) {
          doc.addPage();
          rowY = 40;
          currentX = 10;
          headers.forEach((header) => {
            doc.text(header.name, currentX, rowY - 10);
            currentX += header.width;
          });
        }
      });

      doc.setFontSize(12);
      doc.text('Generated by Aditya College Faculty Portal', 10, 290);
      doc.text(`Page 1`, 180, 290);

      doc.save('class_data.pdf');
    };

    viteLogo.onerror = () => {
      console.error('Failed to load the logo image. Please check the path and try again.');
    };
  };

  return (
    <div style={{ padding: '30px', fontFamily: 'Arial, sans-serif' }}>
      <h1 style={{ textAlign: 'center', marginBottom: '30px', color: '#333' }}>Class Performance Dashboard</h1>

      {classes.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {classes.map((classItem) => {
            const generateLink = () => {
              const link = `http://localhost:5173/rate/${classItem._id}`;
              navigator.clipboard.writeText(link);
              alert('Link copied to clipboard!');
            };

            return (
              <div
                key={classItem._id}
                style={{
                  border: '1px solid #ccc',
                  borderRadius: '8px',
                  padding: '20px',
                  backgroundColor: '#fdfdfd',
                  boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
                  width: '100%',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '15px' }}>
                  <h3 style={{ margin: 0, fontSize: '1.5rem', color: '#4CAF50' }}>
                    {classItem.courseName}
                  </h3>
                  <span style={{
                    backgroundColor: '#4CAF50',
                    color: '#fff',
                    padding: '5px 10px',
                    borderRadius: '20px',
                    fontSize: '0.9rem',
                    fontWeight: 'bold',
                  }}>
                    Rating: {classItem.rating}
                  </span>
                </div>

                <div style={{
                  display: 'grid',
                  gridTemplateColumns: '1fr 1fr',
                  gap: '15px',
                  fontSize: '0.9rem',
                  lineHeight: '1.6',
                }}>
                  <div>
                    <p><strong>Attended:</strong> {classItem.appeared}</p>
                    <p><strong>Semester:</strong> {classItem.semester}</p>
                    <p><strong>Branch:</strong> {classItem.branch}</p>
                  </div>
                  <div>
                    <p><strong>Section:</strong> {classItem.section}</p>
                    <p><strong>Number of Students:</strong> {classItem.numberOfStudents}</p>
                    <p><strong>Pass Percentage:</strong> {classItem.passPercentage}%</p>
                  </div>
                </div>

                <div style={{
                  marginTop: '20px',
                  padding: '10px',
                  backgroundColor: '#f9f9f9',
                  borderRadius: '5px',
                  border: '1px solid #eee',
                }}>
                  <MyPieChart id={`chart-${classItem._id}`} chartData={generateChartData(classItem)} />
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginTop: '20px' }}>
                  <span style={{ fontSize: '1rem', color: '#333', fontWeight: '500' }}>
                    Share this link to the Students for Feedback
                  </span>
                  <button onClick={generateLink} style={{
                    padding: '10px 15px',
                    backgroundColor: "rgb(117 117 117)",
                    color: '#fff',
                    width: '150px',
                    border: 'none',
                    borderRadius: '5px',
                    cursor: 'pointer',
                    transition: 'background-color 0.3s ease',
                  }} onMouseOver={(e) => e.currentTarget.style.backgroundColor = '#45a049'}
                    onMouseOut={(e) => e.currentTarget.style.backgroundColor = '#rgb(117 117 117)'}>Share Link</button>
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <p style={{ textAlign: 'center', fontSize: '18px', color: '#FF5722' }}>No classes found.</p>
      )}

      <button onClick={downloadPDF} style={{
        padding: '10px 15px',
        backgroundColor: '#FF5722',
        color: '#fff',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        transition: 'background-color 0.3s ease',
      }}>
        Download Report
      </button>
    </div>
  );
};

export default OthersClass;
